name: confluent-kafka-go
lang: go
lang_version: 1.21
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/confluent-kafka-go
semaphore:
  enable: true
  pipeline_enable: false
  tasks:
    - name: create-git-tag
      branch: main
      pipeline_file: .semaphore/create-git-tag.yml
      parameters:
        - name: TAG_NAME
          required: true
          description: The name of the tag to be created.
          default_value: "X.Y.Z"
sonarqube:
  enable: true
  coverage_exclusions:
    - "examples/**"
    - "**/*.pb.*"
    - "**/mk-include/**/*"
  coverage_reports:
    - "**/*coverage.txt"
