name: confluent-kafka-go
lang: go
lang_version: 1.21
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/confluent-kafka-go
semaphore:
  enable: true
  pipeline_enable: false
sonarqube:
  enable: true
  coverage_exclusions:
    - "examples/**"
    - "**/*.pb.*"
    - "**/mk-include/**/*"
  coverage_reports:
    - "**/*coverage.txt"
